import { pool } from "../../../db/pool";
import { log } from "../../lib/logger";

// Groq only ever fills these slot enums -- it never generates the reply
// text itself. That's the X automation-rules compliance boundary: parsing/
// classifying intent via AI is fine, generating user-facing text is not
// without prior written approval.
export type MissingSlot =
  | "missing_amount"
  | "missing_token"
  | "missing_recipient_count"
  | "ambiguous_target"
  | "missing_requirement_threshold"
  | "missing_description"
  | "missing_counterparty";

// Full, standalone question -- used verbatim when exactly one slot is
// missing, so a single-slot follow-up still reads as a normal question
// rather than an oddly-short list.
const CLARIFICATION_QUESTIONS: Record<MissingSlot, string> = {
  missing_amount: "How much should this send/give away in total?",
  missing_token: "Which token -- ETH or USDG?",
  missing_recipient_count: "How many people should this go to?",
  ambiguous_target: "Who should receive this -- a hashtag, wallet, X account, or token holders?",
  missing_requirement_threshold: "What's the minimum -- likes, comments, or retweets -- for this giveaway?",
  missing_description: "What's the work or deliverable this escrow is for?",
  missing_counterparty: "Who's the other side of this escrow -- what's their @handle?",
};

// Short, lowercase, comma-joinable fragments -- used when two or more slots
// are missing at once, so they can be combined into one reply instead of
// asking one at a time across several replies.
const CLARIFICATION_FRAGMENTS: Record<MissingSlot, string> = {
  missing_amount: "how much (and which token) to give away in total",
  missing_token: "which token -- ETH or USDG",
  missing_recipient_count: "how many people this should go to",
  ambiguous_target: "who should receive it -- a hashtag, wallet, X account, or token holders",
  missing_requirement_threshold: "the minimum likes/comments/retweets needed",
  missing_description: "what the work/deliverable is",
  missing_counterparty: "who the other side is (their @handle)",
};

// A user gets at most ONE follow-up per request (confirmed 2026-07-20) --
// every missing slot from the first pass is asked here together, in one
// reply, rather than one slot per round-trip. Fixed template text either
// way, keyed off Groq's structured slots, never generated by the model.
export function buildClarificationReply(missingSlots: MissingSlot[]): string {
  if (missingSlots.length === 1) return CLARIFICATION_QUESTIONS[missingSlots[0]!];
  const fragments = missingSlots.map((slot) => CLARIFICATION_FRAGMENTS[slot]);
  return `A few things I need: ${fragments.join("; ")}. Reply with all of it in one message.`;
}

// Fixed fallback once the one follow-up still doesn't resolve -- no further
// asking after this, so the user always knows what actually worked or
// didn't within at most three messages: their post, this bot's one
// follow-up, and this final reply (or a completed transaction instead of
// this reply, if the follow-up did resolve it).
export const COULD_NOT_PROCESS_REPLY =
  "Couldn't process that request. Here's what I understand:\n" +
  "- send AMOUNT eth/usdg to @handle / #hashtag / 0xaddress\n" +
  "- swap AMOUNT eth to SYMBOL (or buy SYMBOL with AMOUNT eth/usdg)\n" +
  "- giveaway AMOUNT to N random people who liked/commented/retweeted this\n" +
  "- airdrop the top N holders of 0xtoken AMOUNT\n" +
  "- airdrop users who bullposted KEYWORD AMOUNT\n" +
  '- $cause create "name" goal: AMOUNT wallet: 0xaddress\n' +
  '- $cause donate AMOUNT #CAUSE-ID / $donate AMOUNT to "name"\n' +
  '- $escrow "description" AMOUNT @handle, then $accept / $deliver / $release / $cancel\n' +
  "- $psend AMOUNT eth/usdg to @handle, then $claim";

export interface PendingClarification {
  xUserId: string;
  source: "mention" | "dm";
  sourceRef: string;
  partialIntent: Record<string, unknown>;
  missingSlots: MissingSlot[];
}

// At most one open clarification per user (see the unique index) -- a new
// one for the same user replaces whatever was open before, and extends the
// 30-minute window fresh from now.
export async function saveClarification(input: PendingClarification): Promise<void> {
  await pool.query(
    `INSERT INTO pending_clarifications (x_user_id, source, source_ref, partial_intent, missing_slots)
     VALUES ($1, $2, $3, $4, $5)
     ON CONFLICT (x_user_id) DO UPDATE SET
       source = EXCLUDED.source,
       source_ref = EXCLUDED.source_ref,
       partial_intent = EXCLUDED.partial_intent,
       missing_slots = EXCLUDED.missing_slots,
       created_at = now(),
       expires_at = now() + interval '30 minutes'`,
    [input.xUserId, input.source, input.sourceRef, JSON.stringify(input.partialIntent), JSON.stringify(input.missingSlots)],
  );
}

export async function getOpenClarification(xUserId: string): Promise<PendingClarification | null> {
  const { rows } = await pool.query(
    `SELECT x_user_id, source, source_ref, partial_intent, missing_slots
     FROM pending_clarifications WHERE x_user_id = $1 AND expires_at > now()`,
    [xUserId],
  );
  if (rows.length === 0) return null;
  const row = rows[0];
  return {
    xUserId: row.x_user_id,
    source: row.source,
    sourceRef: row.source_ref,
    partialIntent: row.partial_intent,
    missingSlots: row.missing_slots,
  };
}

export async function clearClarification(xUserId: string): Promise<void> {
  await pool.query("DELETE FROM pending_clarifications WHERE x_user_id = $1", [xUserId]);
}

// No reply sent for anything this sweeps up -- avoids spending a
// reply-write on a conversation the user already walked away from.
export async function sweepExpiredClarifications(): Promise<void> {
  const { rowCount } = await pool.query("DELETE FROM pending_clarifications WHERE expires_at <= now()");
  if (rowCount) log.info("pending_clarifications_expired", { count: rowCount });
}
