import Groq from "groq-sdk";
import { config } from "../../config";
import type { MissingSlot } from "./clarificationService";

// Deterministic, keyword-triggered parsing (commandParser.ts) covers send
// and swap -- both are unambiguous once the regex matches. Giveaway and
// airdrop requests are phrased too freely for a fixed regex ("send 0.0005
// eth to any random 20 users in the comments," worded however), so this
// module classifies free text via Groq instead. Output is consumed as data
// only: every user-facing reply stays a fixed template keyed off these
// slots, never generated by the model itself -- that's the X automation
// -rules compliance boundary (parsing intent via AI is fine, generating the
// reply text is not, without prior written approval).
export type ParsedIntentAction = "giveaway" | "airdrop" | "unrecognized";
export type AirdropMode = "hold" | "bullpost";
export type RequirementType = "likes" | "comments" | "retweets";

export interface ParsedIntent {
  action: ParsedIntentAction;
  amount: number | null;
  token: "eth" | "usdg" | null;
  // Giveaway slots
  winnerCount: number | null;
  requirementType: RequirementType | null;
  requirementThreshold: number | null;
  // Airdrop slots (Wave 4) -- parsed here since one shared classifier
  // covers both intents, even though only Wave 3 consumes giveaway slots
  // so far.
  airdropMode: AirdropMode | null;
  tokenAddress: string | null; // hold-airdrop's target token contract
  keyword: string | null; // bullpost-airdrop's search keyword
  recipientCount: number | null; // bullpost-airdrop's headcount
  confidence: number;
  // Every slot still missing, not just one -- a user gets at most one
  // follow-up per request (confirmed 2026-07-20), so the first pass has to
  // surface everything it needs at once instead of one thing per round-trip.
  missingSlots: MissingSlot[];
}

/** Whatever slots a prior turn already gathered, for merging a short
 * follow-up reply ("20 people, eth", "likes, 5") into a complete intent
 * instead of parsing it as a brand new, context-free instruction. */
export interface PriorIntentContext {
  partialIntent: Record<string, unknown>;
  missingSlots: MissingSlot[];
}

const SYSTEM_INSTRUCTION = `You parse free-text giveaway and airdrop requests for TagioPay, a bot on Robinhood Chain (tokenized equities + ETH + USDG).

Classify into exactly one of: "giveaway", "airdrop", "unrecognized".

"giveaway" is a luck-based request to pick random winners from people who engaged with a post -- "send 0.0005 eth to any random 20 users in the comments," "giveaway 50 usdg to 10 random people who liked this," worded however. Extract: amount, token ("eth" or "usdg"), winnerCount (how many winners), requirementType (exactly one of "likes", "comments", "retweets" -- whichever engagement the winners must have given), requirementThreshold (the minimum count of that engagement needed before winners are picked, default to 1 if the user didn't state a specific number). If winnerCount is missing, that is a "missing_recipient_count" clarification -- the same slot used for bullpost-airdrop's headcount below, since both are really just "how many people should this go to."

"airdrop" is a merit-based request with no random luck involved, paid immediately without waiting. Two kinds -- set airdropMode to "hold" or "bullpost":
- "hold": pays existing holders of a token, proportional to their balance -- "airdrop the top 50 holders of 0x1234... 0.3 eth". Extract tokenAddress (the contract address given) and amount/token. If the message is clearly a hold-airdrop but gives no contract address at all, that is an "ambiguous_target" clarification (there's no other way to say who "the holders" even are).
- "bullpost": pays people who posted about a keyword recently, proportional to engagement -- "airdrop users who bullposted $HOOD 40 usdg". Extract keyword (what they posted about) and recipientCount (how many people to pay, if stated) and amount/token.

"unrecognized" is anything that isn't clearly a giveaway or airdrop request -- an ordinary reply, a question, spam, or anything else. Use this whenever you're not confident it's actually one of the two.

Respond with ONLY a JSON object matching exactly this shape (no markdown, no extra keys):
{"action": "giveaway"|"airdrop"|"unrecognized", "amount": number|null, "token": "eth"|"usdg"|null, "winnerCount": number|null, "requirementType": "likes"|"comments"|"retweets"|null, "requirementThreshold": number|null, "airdropMode": "hold"|"bullpost"|null, "tokenAddress": string|null, "keyword": string|null, "recipientCount": number|null, "confidence": number, "missingSlots": ("missing_amount"|"missing_token"|"missing_recipient_count"|"ambiguous_target"|"missing_requirement_threshold")[]}

- Only fill slots relevant to the classified action; leave every other slot null.
- "confidence" is your confidence in the classification, 0 to 1.
- "missingSlots" lists EVERY slot required to actually execute the request that's still missing -- not just the first one you notice. Include as many as apply: missing_amount (no amount/token given), missing_token (amount given but not which token), missing_recipient_count (bullpost-airdrop with no headcount), ambiguous_target (unclear who should receive it), missing_requirement_threshold (giveaway with no clear engagement type). Empty array when nothing required is missing.
- Never invent an amount, token, count, address, or keyword that wasn't stated or clearly implied. When in doubt, lower confidence and list the relevant slot in missingSlots instead of guessing.

Sometimes the message includes a "PRIOR TURN" block -- the slots already gathered earlier in this same conversation, plus which slots were asked for (this is the user's ONE AND ONLY follow-up reply -- there will be no second chance, so extract everything this reply answers as generously as reasonable). The new message is almost always a short, incomplete answer to that question ("eth, 20 people", "likes, 5", "20"), not a fresh standalone instruction. Merge it into the prior turn: keep the prior action and every prior field the new message doesn't touch, fill in whatever the new message answers, and only discard the prior context if the new message is unambiguously a different, self-contained instruction. Set missingSlots to whatever, if anything, is still missing after merging -- this will NOT be asked again, so only list something here if it truly can't be inferred.`;

// Free-tier rate limit (not a shrinking credit balance): 30 req/min --
// queue FIFO and wait for a slot in a rolling 60s window rather than
// erroring on a burst (e.g. a full 20-mention poll batch all needing a
// Groq call in the same tick).
const MODEL = "llama-3.3-70b-versatile";
const RATE_LIMIT_PER_MIN = 30;
const WINDOW_MS = 60_000;

let client: Groq | null = null;
function getClient(): Groq {
  client ??= new Groq({ apiKey: config.groq.apiKey });
  return client;
}

const callTimestamps: number[] = [];
let queueTail: Promise<unknown> = Promise.resolve();

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function waitForSlot(): Promise<void> {
  for (;;) {
    const now = Date.now();
    while (callTimestamps.length && now - callTimestamps[0]! >= WINDOW_MS) {
      callTimestamps.shift();
    }
    if (callTimestamps.length < RATE_LIMIT_PER_MIN) {
      callTimestamps.push(now);
      return;
    }
    await sleep(callTimestamps[0]! + WINDOW_MS - now + 5);
  }
}

function scheduleGroqCall<T>(fn: () => Promise<T>): Promise<T> {
  const result = queueTail.then(async () => {
    await waitForSlot();
    return fn();
  }) as Promise<T>;
  queueTail = result.catch(() => {});
  return result;
}

function buildUserContent(message: string, prior?: PriorIntentContext): string {
  if (!prior) return message;
  return `PRIOR TURN (already gathered this conversation): ${JSON.stringify(prior.partialIntent)}\nYou asked about: ${JSON.stringify(prior.missingSlots)}\nUser's reply (their one and only follow-up -- there is no second chance after this): ${message}`;
}

export async function parseIntent(message: string, prior?: PriorIntentContext): Promise<ParsedIntent> {
  const response = await scheduleGroqCall(() =>
    getClient().chat.completions.create({
      model: MODEL,
      messages: [
        { role: "system", content: SYSTEM_INSTRUCTION },
        { role: "user", content: buildUserContent(message, prior) },
      ],
      response_format: { type: "json_object" },
      temperature: 0,
    }),
  );

  const text = response.choices[0]?.message?.content;
  if (!text) throw new Error("Groq returned an empty response");

  const parsed = JSON.parse(text) as Partial<ParsedIntent>;

  return {
    action: oneOf(parsed.action, ["giveaway", "airdrop", "unrecognized"] as const, "unrecognized") ?? "unrecognized",
    amount: parsed.amount ?? null,
    token: oneOf(parsed.token, ["eth", "usdg"], null),
    winnerCount: parsed.winnerCount ?? null,
    requirementType: oneOf(parsed.requirementType, ["likes", "comments", "retweets"], null),
    requirementThreshold: parsed.requirementThreshold ?? null,
    airdropMode: oneOf(parsed.airdropMode, ["hold", "bullpost"], null),
    tokenAddress: parsed.tokenAddress ?? null,
    keyword: parsed.keyword ?? null,
    recipientCount: parsed.recipientCount ?? null,
    confidence: parsed.confidence ?? 0,
    // The JSON-object response mode only guarantees valid JSON syntax, not
    // adherence to the enum described in the prompt -- confirmed live: Groq
    // once returned "missing_winner_count" here, a value that doesn't exist
    // in the reply bank (clarificationService.ts's CLARIFICATION_QUESTIONS),
    // which would have looked up as undefined with no defensive check. Same
    // defensive filtering now applied per-element of the array: any
    // hallucinated value outside the known enum is dropped, not kept.
    missingSlots: oneOfArray(parsed.missingSlots, [
      "missing_amount",
      "missing_token",
      "missing_recipient_count",
      "ambiguous_target",
      "missing_requirement_threshold",
    ] as const),
  };
}

function oneOf<T extends string>(value: unknown, allowed: readonly T[], fallback: T | null): T | null {
  return typeof value === "string" && (allowed as readonly string[]).includes(value) ? (value as T) : fallback;
}

function oneOfArray<T extends string>(value: unknown, allowed: readonly T[]): T[] {
  if (!Array.isArray(value)) return [];
  return value.filter((v): v is T => typeof v === "string" && (allowed as readonly string[]).includes(v));
}
