/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FacebookRouteImport } from './routes/facebook'
import { Route as NftsRouteImport } from './routes/nfts'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PayTargetRouteImport } from './routes/pay.$target'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookRoute = FacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsRoute = NftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTargetRoute = PayTargetRouteImport.update({
  id: '/pay/$target',
  path: '/pay/$target',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/facebook': typeof FacebookRoute
  '/nfts': typeof NftsRoute
  '/roadmap': typeof RoadmapRoute
  '/trade': typeof TradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/pay/$target': typeof PayTargetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/facebook': typeof FacebookRoute
  '/nfts': typeof NftsRoute
  '/roadmap': typeof RoadmapRoute
  '/trade': typeof TradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/pay/$target': typeof PayTargetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/facebook': typeof FacebookRoute
  '/nfts': typeof NftsRoute
  '/roadmap': typeof RoadmapRoute
  '/trade': typeof TradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/pay/$target': typeof PayTargetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/facebook'
    | '/nfts'
    | '/roadmap'
    | '/trade'
    | '/auth/callback'
    | '/pay/$target'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/dashboard'
    | '/facebook'
    | '/nfts'
    | '/roadmap'
    | '/trade'
    | '/auth/callback'
    | '/pay/$target'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/facebook'
    | '/nfts'
    | '/roadmap'
    | '/trade'
    | '/auth/callback'
    | '/pay/$target'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DashboardRoute: typeof DashboardRoute
  FacebookRoute: typeof FacebookRoute
  NftsRoute: typeof NftsRoute
  RoadmapRoute: typeof RoadmapRoute
  TradeRoute: typeof TradeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PayTargetRoute: typeof PayTargetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook': {
      id: '/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof FacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts': {
      id: '/nfts'
      path: '/nfts'
      fullPath: '/nfts'
      preLoaderRoute: typeof NftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$target': {
      id: '/pay/$target'
      path: '/pay/$target'
      fullPath: '/pay/$target'
      preLoaderRoute: typeof PayTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DashboardRoute: DashboardRoute,
  FacebookRoute: FacebookRoute,
  NftsRoute: NftsRoute,
  RoadmapRoute: RoadmapRoute,
  TradeRoute: TradeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PayTargetRoute: PayTargetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
