/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XCommandsListRouteImport } from './routes/x-commands-list'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HNameRouteImport } from './routes/h.$name'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const XCommandsListRoute = XCommandsListRouteImport.update({
  id: '/x-commands-list',
  path: '/x-commands-list',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HNameRoute = HNameRouteImport.update({
  id: '/h/$name',
  path: '/h/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/x-commands-list': typeof XCommandsListRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/h/$name': typeof HNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/x-commands-list': typeof XCommandsListRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/h/$name': typeof HNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/x-commands-list': typeof XCommandsListRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/h/$name': typeof HNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/x-commands-list'
    | '/auth/callback'
    | '/h/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/x-commands-list' | '/auth/callback' | '/h/$name'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/x-commands-list'
    | '/auth/callback'
    | '/h/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  XCommandsListRoute: typeof XCommandsListRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  HNameRoute: typeof HNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x-commands-list': {
      id: '/x-commands-list'
      path: '/x-commands-list'
      fullPath: '/x-commands-list'
      preLoaderRoute: typeof XCommandsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$name': {
      id: '/h/$name'
      path: '/h/$name'
      fullPath: '/h/$name'
      preLoaderRoute: typeof HNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  XCommandsListRoute: XCommandsListRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  HNameRoute: HNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
